### ISSUE TITLE
Sorry for my ignorance but how do I install the Nautilus Python dep?

### ISSUE THREAD

**Issue by thedonquixotic** [flozz/nautilus-terminal#13]
I don't see any install commands to install it. Sorry, I'm new to Linux.

**Comment by flozz** [comment]
Hello,

It depends of your distribution. For Debian / Ubuntu you can install it with

    sudo apt install python-nautilus

:)

**Comment by thedonquixotic** [comment]
Thanks! I'm going to try and get this terminal extension installed later today. The python command worked. Closing ticket. Thanks again!

**Comment by flozz** [comment]
I already thought about making a logo, but I never done it because I wanted to do a GUI first... And I also wanted to do a better documentation (both for developers and users)... So there is a lot to do and any help is welcome :)

And yes, design / UX is a recurrent problem with Free and Open Source software. I am convinced that a non-ergonomic interface and a non-existing / ugly design makes users run away, even if the software does its job well.

**Comment by thedonquixotic** [comment]
Cool. I'll add you to my ongoing list of projects that I'm going to try and make logos for etc.

**Comment by thedonquixotic** [comment]
https://github.com/thedonquixotic/Open-Source-Branding
